[*]
wallpaper_mode=crop
wallpaper_common=1
wallpaper=@WALLPAPER_PATH@
desktop_bg=#000000
desktop_fg=#ececec
desktop_shadow=#000000
desktop_font=Inter 10
show_wm_menu=1
sort=ascending;byname;
show_documents=0
show_trash=0
show_mounts=0
